### ISSUE TITLE
CLIP ViT/B-32 reproduction

### ISSUE THREAD

**Issue by Zhengsh123** [rezazzr/breadcrumbs#7]
This is an excellent work. 
However, I encountered a small issue during the reproduction process. I tested it on CLIP ViT/B-32 using your publicly available code and the optimal configuration mentioned in the paper: alpha=1, beta=0.1, gamma=0.01. However, the performance I obtained on the 8 test datasets is significantly lower than the average value (83.35%) mentioned in the paper. Below are the performance values I got for each dataset: Cars: 62.12%; DTD: 64.04%; EuroSAT: 87.11%; GTSRB: 76.48%; MNIST: 98.92%; RESISC45: 77.16%; SVHN: 85.86%. 
Do you know what might be causing this discrepancy? Thanks.

**Comment by rezazzr** [comment]
Hi @Zhengsh123 😊

Thank you so much for your interest in our work and for taking the time to reproduce the results.

I believe the discrepancy you're seeing is due to how the performance is calculated. The values reported in the paper are **Average Normalized Accuracy**, as detailed in [Equation (4)](https://arxiv.org/pdf/2312.06795) of our paper. If you used raw accuracy and averaged them directly, the results would indeed differ from the normalized averages we reported.

Could you please verify this and let me know if it resolves the issue? If you have any further questions, feel free to ask—I'm happy to help!

Best regards,  
Reza

**Comment by Zhengsh123** [comment]
Hi @rezazzr, thank you very much for your response. I realized that I had misunderstood the evaluation metric. After correcting the metric, my performance values are similar to those in the paper. Thanks again—this is a great piece of work!

Best regards,
Shenghe
